name: Automated testing

on: [push]

jobs:
  call-testing-workflow:
    uses: digitalutsc/reusable_workflows/.github/workflows/ci-testing.yml@main
    with:
      module_name: advancedqueue_runner
      composer_name: digitalutsc/advancedqueue_runner
      test_suite: functional
